### ISSUE TITLE
Automatic dash components static files collection

### ISSUE THREAD

**Issue by min0ru** [pikhovkin/dj-plotly-dash#10]
Right now we need to manually collect and copy dash component files to django static directory.
It seems convenient to me that it should be automated with django collectstatic command.

**Comment by pikhovkin** [comment]
Added in release [0.8.1](https://github.com/pikhovkin/dj-plotly-dash/releases/tag/0.8.1) (https://github.com/pikhovkin/dj-plotly-dash/commit/cef320a183c6d0e886ac90c21185080333ac8594)
