### ISSUE TITLE
Is every view invocation starting a new dash server?

### ISSUE THREAD

**Issue by martinwk** [pikhovkin/dj-plotly-dash#63]
Hi I am not sure whether to ask the question here, but could not find a better place. I wondered, Is every view invocation starting a new dash server? If so this would mean that the amount of running dash servers increases over time which is not desirable I think. I could not deduct it from the source code whether this happens. All I could see was that with basic view `dash = Dash()` seems to start a new  Dash server. I am not sure, does this mean it is started only once for every View I define, because it is a class attribute? Or is it starting every time the view is requested?

**Comment by pikhovkin** [comment]
Hi!
If you ask in the context of the dj_plotly_dash then my answer is no. There will be only one server is a django server, but in the views will create Dash objects. These objects do not contain a dependency on Flask as in the original library from Plotly.

**Comment by martinwk** [comment]
Hi! Oke, that sounds like a proper implementation. So you basically took out the flask dependency and made it work with the django back-end instead. I will explore more of this package soon! Thanks for your quick reply.
